---

inventory:
  plugin: SimpleInventory
  options:
    host_file: "prod_hosts.yaml"
    group_file: "groups.yaml"
    defaults_file: "defaults.yaml"

runner:
  plugin: threaded
  options: 
    num_workers: 4